"""Initial schema

Revision ID: 8004a576854d
Revises: 
Create Date: 2026-06-14 02:28:54.152979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8004a576854d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_rate_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_label', sa.String(length=50), nullable=False),
    sa.Column('min_weight_lbs', sa.Integer(), nullable=False),
    sa.Column('max_weight_lbs', sa.Integer(), nullable=False),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('flat_rate_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_per_lb_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('parish', sa.String(length=50), nullable=False),
    sa.Column('trn_encrypted', sa.Text(), nullable=False),
    sa.Column('trn_hash', sa.String(length=64), nullable=False),
    sa.Column('shipping_id', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_shipping_id'), ['shipping_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_trn_hash'), ['trn_hash'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=160), nullable=True),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('carrier_tracking', sa.String(length=100), nullable=True),
    sa.Column('label_name', sa.String(length=255), nullable=True),
    sa.Column('label_boss_id', sa.String(length=20), nullable=True),
    sa.Column('shipper', sa.String(length=30), nullable=True),
    sa.Column('actual_weight_lbs', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('billable_weight_lbs', sa.Integer(), nullable=True),
    sa.Column('shipping_cost_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_tier_label', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_tracking_number'), ['tracking_number'], unique=True)

    op.create_table('package_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('r2_object_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pre_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('carrier_tracking', sa.String(length=100), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('declared_value_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice_object_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pre_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pre_alerts_carrier_tracking'), ['carrier_tracking'], unique=False)
        batch_op.create_index(batch_op.f('ix_pre_alerts_customer_id'), ['customer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pre_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pre_alerts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_pre_alerts_carrier_tracking'))

    op.drop_table('pre_alerts')
    op.drop_table('package_photos')
    op.drop_table('package_events')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_tracking_number'))

    op.drop_table('packages')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_trn_hash'))
        batch_op.drop_index(batch_op.f('ix_users_shipping_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('shipping_rate_tiers')
    # ### end Alembic commands ###
